### ISSUE TITLE
Water not rendering on iOS

### ISSUE THREAD

**Issue by milox** [Unity-Technologies/boat-attack-water#3]
I have the depth and opaque texture enabled, but the water doesn't show up on iOS 15 (iPhone 6s). Using Unity 2020.3 LTS. Works on all other platforms. Original water from Boat Attack demo also works.

Expected result:
![rendered](https://user-images.githubusercontent.com/815222/154611837-5b3fc1d8-d2e0-48ae-9db4-7c203121e118.png)

What I get:
![not rendered](https://user-images.githubusercontent.com/815222/154611849-3e914a2d-6be5-4e63-9a42-97d3dc0fd288.png)

**Comment by TYTbetter** [comment]
我也遇到同样的问题，同求解，谢谢！

**Comment by TYTbetter** [comment]
补充信息：
unity2020.3.29f1c1
MacBook Pro (16-inch,2019) + macOS Big Sur
在MacBookPro上，android 正常，Mac正常，就是Ios没有水。

**Comment by milox** [comment]
Seems the issue was fixed with in this commit 69116042d09ed80a1bb1f7842bfe93c6b9859896
